apiVersion: v1
kind: Service
metadata:
  name: kubernetesexample-service
  namespace: kubernetesexample
spec:
  type: LoadBalancer
  selector:
    app: kubernetesexample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080